### ISSUE TITLE
LabyrinthProvider.getInstance() returning null

### ISSUE THREAD

**Issue by Allstreamer** [the-h-team/Labyrinth#13]
Apparently labyrinth.formatting.string.ColoredString.toString:
<pre lang="java">
/**
 * Translate the text within a string body to color
 */
public String toString() {
	String r = "No context to return";
	switch (chosen) {
		case MC:
			r = ChatColor.translateAlternateColorCodes('&', text);
			break;
		case MC_COMPONENT:
			r = "Cannot convert raw component to String";
			break;
		case HEX:
                        // Fails Here ↓
			if (LabyrinthProvider.getInstance().isLegacy()) {
				r = ChatColor.translateAlternateColorCodes('&', text);
			} else {
				r = ChatColor.translateAlternateColorCodes('&', RGBApi.toColoredMessage(text));
			}
			break;
	}
	return r;
}
</pre>

Fails to get the LabyrinthProvider instance.

Here is the error i get:
```Java
[01:21:34 ERROR]: Error occurred while enabling myEssentials v1.0.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.github.sanctum.labyrinth.api.LabyrinthAPI.isLegacy()" because the return value of "com.github.sanctum.labyrinth.LabyrinthProvider.getInstance()" is null
        at com.github.sanctum.labyrinth.formatting.string.ColoredString.toString(ColoredString.java:50) ~[?:?]
        at com.github.sanctum.labyrinth.library.StringUtils.translate(StringUtils.java:92) ~[?:?]
        at com.github.sanctum.myessentials.Essentials.onEnable(Essentials.java:92) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-783]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-783]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-783]
        at java.lang.Thread.run(Thread.java:831) [?:?]```
        
IDK if I'm missing something obvious or this is an actual thing

**Comment by ms5984** [comment]
send me the pom @Allstreamer
